appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure, win: appveyor}
travis:
  secure: {BINSTAR_TOKEN: frNM8AHOb3Jjf6oQPaKUzk1WDv2ZDrQX8MNd7McGYt7Zid+syZtcBZPNV7DMoCqg5PhyaPJ5fKLGNoW09vt/PffWdmEWFvWUWmjmnnJDe1XC6IkwE5Ap1KUM3rfFvLlIy+YBHAQT/I6Lm9OCVGw/R/2AHqYiIAEm1mTelKUf7Bjz7lD1BtUUh4j8neh4TIYPBMOHF6wiSbTlqPVcgymOvChP/j1WsEOMe3PI3u0ndeuRWDFL4K0rqZbhC4WkZfuIxXYwistSCKaWSBrd8so9zrfaJjaVuozp0PWpIOvGQuqkB3UP5ny/J5Cwqc8hzkt0H0nn9p1d4HviKQKAoOUQkmvx6J2CSEs0P+Z/SDpUwpK9V/hTPK0GI04wQYYJGOmXaazLapBCUqR5OxZ2BDiszoWh8/gn84aWn58UmEYQLHUEGB48Ud3gWhpDO6wgUZAlsaNYYU3SQH5Z7/WamkBiOMmT1OA0kU62syqNvlpb9udWC72jR21dZogIODJITB6/a9NUpGn9j3XotJQNg1A9zStZDZAdnzjn8p5yMnLYwC8aX9PMMEcfiA4usp9tRmnSmsWkY+xrfdsh+gek8Ws2sDkDfT634nI8m73fjlzkxmTcGfrW7Wq/R9HGYIWIXJ+b7SiBpA5kbOK8YbaFswgHKQ3BBueHhJ6Lsh2TdiQAhOQ=}
